### PR TITLE
OCI Monitoring Post Metric example

### PR DESCRIPTION
**Pull request by naikvenu**
This is an example to Post custom metric to OCI monitoring. 
https://docs.cloud.oracle.com/en-us/iaas/api/#/en/monitoring/20180401/datatypes/MetricDataDetails

### CODE REVIEW

**Comment by waruwaruwaru** [comment]
Hi @naikvenu, 

Can we have an example for JavaScript as well? Thank you.

**Comment by naikvenu** [comment]
> Hi @naikvenu,
> 
> Can we have an example for TypeScript as well? Thank you.

Thanks Walt, Will post it by tommorow.

**Comment by naikvenu** [comment]
@waruwaruwaru have posted typescript example.

**Comment by naikvenu** [comment]
@waruwaruwaru  Changed the values to generic.

**Review by waruwaruwaru — APPROVED** [review]

**Pull request merged**
